var wms_layers = [];

var lyr_GlobalMultiResolutionTopographyGMRTSynthesis_0 = new ol.layer.Tile({
                            source: new ol.source.TileWMS(({
                              url: "https://www.gmrt.org/services/mapserver/wms_merc?",
    attributions: ' ',
                              params: {
                                "LAYERS": "GMRT",
                                "TILED": "true",
                                "VERSION": "1.3.0"},
                            })),
                            title: "Global Multi-Resolution Topography (GMRT) Synthesis",
                            opacity: 1.000000,
                            
                            
                          });
              wms_layers.push([lyr_GlobalMultiResolutionTopographyGMRTSynthesis_0, 1]);
var format_ClovisseArctique_AireConcentration_1 = new ol.format.GeoJSON();
var features_ClovisseArctique_AireConcentration_1 = format_ClovisseArctique_AireConcentration_1.readFeatures(json_ClovisseArctique_AireConcentration_1, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_ClovisseArctique_AireConcentration_1 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_ClovisseArctique_AireConcentration_1.addFeatures(features_ClovisseArctique_AireConcentration_1);
var lyr_ClovisseArctique_AireConcentration_1 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_ClovisseArctique_AireConcentration_1, 
                style: style_ClovisseArctique_AireConcentration_1,
                popuplayertitle: "ClovisseArctique_AireConcentration",
                interactive: true,
                title: '<img src="styles/legend/ClovisseArctique_AireConcentration_1.png" /> ClovisseArctique_AireConcentration'
            });
var format_CouteauAtlantique_AireConcentration_2 = new ol.format.GeoJSON();
var features_CouteauAtlantique_AireConcentration_2 = format_CouteauAtlantique_AireConcentration_2.readFeatures(json_CouteauAtlantique_AireConcentration_2, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_CouteauAtlantique_AireConcentration_2 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_CouteauAtlantique_AireConcentration_2.addFeatures(features_CouteauAtlantique_AireConcentration_2);
var lyr_CouteauAtlantique_AireConcentration_2 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_CouteauAtlantique_AireConcentration_2, 
                style: style_CouteauAtlantique_AireConcentration_2,
                popuplayertitle: "CouteauAtlantique_AireConcentration",
                interactive: true,
                title: '<img src="styles/legend/CouteauAtlantique_AireConcentration_2.png" /> CouteauAtlantique_AireConcentration'
            });
var format_MactreAtlantique_AireConcentration_3 = new ol.format.GeoJSON();
var features_MactreAtlantique_AireConcentration_3 = format_MactreAtlantique_AireConcentration_3.readFeatures(json_MactreAtlantique_AireConcentration_3, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_MactreAtlantique_AireConcentration_3 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_MactreAtlantique_AireConcentration_3.addFeatures(features_MactreAtlantique_AireConcentration_3);
var lyr_MactreAtlantique_AireConcentration_3 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_MactreAtlantique_AireConcentration_3, 
                style: style_MactreAtlantique_AireConcentration_3,
                popuplayertitle: "MactreAtlantique_AireConcentration",
                interactive: true,
                title: '<img src="styles/legend/MactreAtlantique_AireConcentration_3.png" /> MactreAtlantique_AireConcentration'
            });
var format_MactreStimpson_AireConcentration_4 = new ol.format.GeoJSON();
var features_MactreStimpson_AireConcentration_4 = format_MactreStimpson_AireConcentration_4.readFeatures(json_MactreStimpson_AireConcentration_4, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_MactreStimpson_AireConcentration_4 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_MactreStimpson_AireConcentration_4.addFeatures(features_MactreStimpson_AireConcentration_4);
var lyr_MactreStimpson_AireConcentration_4 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_MactreStimpson_AireConcentration_4, 
                style: style_MactreStimpson_AireConcentration_4,
                popuplayertitle: "MactreStimpson_AireConcentration",
                interactive: true,
                title: '<img src="styles/legend/MactreStimpson_AireConcentration_4.png" /> MactreStimpson_AireConcentration'
            });
var format_MyeCommune_AireConcentration_5 = new ol.format.GeoJSON();
var features_MyeCommune_AireConcentration_5 = format_MyeCommune_AireConcentration_5.readFeatures(json_MyeCommune_AireConcentration_5, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_MyeCommune_AireConcentration_5 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_MyeCommune_AireConcentration_5.addFeatures(features_MyeCommune_AireConcentration_5);
var lyr_MyeCommune_AireConcentration_5 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_MyeCommune_AireConcentration_5, 
                style: style_MyeCommune_AireConcentration_5,
                popuplayertitle: "MyeCommune_AireConcentration",
                interactive: true,
                title: '<img src="styles/legend/MyeCommune_AireConcentration_5.png" /> MyeCommune_AireConcentration'
            });
var format_Petoncles_AireConcentration_6 = new ol.format.GeoJSON();
var features_Petoncles_AireConcentration_6 = format_Petoncles_AireConcentration_6.readFeatures(json_Petoncles_AireConcentration_6, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Petoncles_AireConcentration_6 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Petoncles_AireConcentration_6.addFeatures(features_Petoncles_AireConcentration_6);
var lyr_Petoncles_AireConcentration_6 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Petoncles_AireConcentration_6, 
                style: style_Petoncles_AireConcentration_6,
                popuplayertitle: "Petoncles_AireConcentration",
                interactive: true,
                title: '<img src="styles/legend/Petoncles_AireConcentration_6.png" /> Petoncles_AireConcentration'
            });

lyr_GlobalMultiResolutionTopographyGMRTSynthesis_0.setVisible(true);lyr_ClovisseArctique_AireConcentration_1.setVisible(true);lyr_CouteauAtlantique_AireConcentration_2.setVisible(true);lyr_MactreAtlantique_AireConcentration_3.setVisible(true);lyr_MactreStimpson_AireConcentration_4.setVisible(true);lyr_MyeCommune_AireConcentration_5.setVisible(true);lyr_Petoncles_AireConcentration_6.setVisible(true);
var layersList = [lyr_GlobalMultiResolutionTopographyGMRTSynthesis_0,lyr_ClovisseArctique_AireConcentration_1,lyr_CouteauAtlantique_AireConcentration_2,lyr_MactreAtlantique_AireConcentration_3,lyr_MactreStimpson_AireConcentration_4,lyr_MyeCommune_AireConcentration_5,lyr_Petoncles_AireConcentration_6];
lyr_ClovisseArctique_AireConcentration_1.set('fieldAliases', {'NAME_EN': 'NAME_EN', 'NAME_FR': 'NAME_FR', 'NAME_SCI': 'NAME_SCI', 'NAME_OTHER': 'NAME_OTHER', 'LABEL_EN': 'LABEL_EN', 'LABEL_FR': 'LABEL_FR', 'URL': 'URL', 'URL_OTHER': 'URL_OTHER', 'LEGISLATIO': 'LEGISLATIO', 'LEGISLAT_1': 'LEGISLAT_1', 'JURISDICTI': 'JURISDICTI', 'JURISDIC_1': 'JURISDIC_1', 'GROUP_EN': 'GROUP_EN', 'GROUP_FR': 'GROUP_FR', 'SUBGROUP_E': 'SUBGROUP_E', 'SUBGROUP_F': 'SUBGROUP_F', 'STATUS_EN': 'STATUS_EN', 'STATUS_FR': 'STATUS_FR', 'DESCRIPTIO': 'DESCRIPTIO', 'DESCRIPT_1': 'DESCRIPT_1', 'VALIDATION': 'VALIDATION', 'PROVINCEEX': 'PROVINCEEX', 'REGION_EN': 'REGION_EN', 'REGION_FR': 'REGION_FR', 'ABUNDANCE': 'ABUNDANCE', 'DATASOURCE': 'DATASOURCE', 'STATUS_COD': 'STATUS_COD', 'SARA_EN': 'SARA_EN', 'SARA_FR': 'SARA_FR', 'SRANK_EN': 'SRANK_EN', 'SRANK_FR': 'SRANK_FR', 'COSEWIC_EN': 'COSEWIC_EN', 'COSEWIC_FR': 'COSEWIC_FR', 'LEMV_EN': 'LEMV_EN', 'LEMV_FR': 'LEMV_FR', 'GRANK_EN': 'GRANK_EN', 'GRANK_FR': 'GRANK_FR', 'ACTIVITY_E': 'ACTIVITY_E', 'ACTIVITY_F': 'ACTIVITY_F', 'LIFESTAGE_': 'LIFESTAGE_', 'LIFESTAGE1': 'LIFESTAGE1', 'IUCN_EN': 'IUCN_EN', 'IUCN_FR': 'IUCN_FR', 'SEASONALIT': 'SEASONALIT', 'SEASONAL_1': 'SEASONAL_1', 'JAN': 'JAN', 'FEB': 'FEB', 'MAR': 'MAR', 'APR': 'APR', 'MAY': 'MAY', 'JUN': 'JUN', 'JUL': 'JUL', 'AUG': 'AUG', 'SEP': 'SEP', 'OCT': 'OCT', 'NOV': 'NOV', 'DEC': 'DEC', 'Shape_Leng': 'Shape_Leng', 'Shape_Area': 'Shape_Area', });
lyr_CouteauAtlantique_AireConcentration_2.set('fieldAliases', {'NAME_EN': 'NAME_EN', 'NAME_FR': 'NAME_FR', 'NAME_SCI': 'NAME_SCI', 'NAME_OTHER': 'NAME_OTHER', 'LABEL_EN': 'LABEL_EN', 'LABEL_FR': 'LABEL_FR', 'URL': 'URL', 'URL_OTHER': 'URL_OTHER', 'LEGISLATIO': 'LEGISLATIO', 'LEGISLAT_1': 'LEGISLAT_1', 'JURISDICTI': 'JURISDICTI', 'JURISDIC_1': 'JURISDIC_1', 'GROUP_EN': 'GROUP_EN', 'GROUP_FR': 'GROUP_FR', 'SUBGROUP_E': 'SUBGROUP_E', 'SUBGROUP_F': 'SUBGROUP_F', 'STATUS_EN': 'STATUS_EN', 'STATUS_FR': 'STATUS_FR', 'DESCRIPTIO': 'DESCRIPTIO', 'DESCRIPT_1': 'DESCRIPT_1', 'VALIDATION': 'VALIDATION', 'PROVINCEEX': 'PROVINCEEX', 'REGION_EN': 'REGION_EN', 'REGION_FR': 'REGION_FR', 'ABUNDANCE': 'ABUNDANCE', 'DATASOURCE': 'DATASOURCE', 'STATUS_COD': 'STATUS_COD', 'SARA_EN': 'SARA_EN', 'SARA_FR': 'SARA_FR', 'SRANK_EN': 'SRANK_EN', 'SRANK_FR': 'SRANK_FR', 'COSEWIC_EN': 'COSEWIC_EN', 'COSEWIC_FR': 'COSEWIC_FR', 'LEMV_EN': 'LEMV_EN', 'LEMV_FR': 'LEMV_FR', 'GRANK_EN': 'GRANK_EN', 'GRANK_FR': 'GRANK_FR', 'ACTIVITY_E': 'ACTIVITY_E', 'ACTIVITY_F': 'ACTIVITY_F', 'LIFESTAGE_': 'LIFESTAGE_', 'LIFESTAGE1': 'LIFESTAGE1', 'IUCN_EN': 'IUCN_EN', 'IUCN_FR': 'IUCN_FR', 'SEASONALIT': 'SEASONALIT', 'SEASONAL_1': 'SEASONAL_1', 'JAN': 'JAN', 'FEB': 'FEB', 'MAR': 'MAR', 'APR': 'APR', 'MAY': 'MAY', 'JUN': 'JUN', 'JUL': 'JUL', 'AUG': 'AUG', 'SEP': 'SEP', 'OCT': 'OCT', 'NOV': 'NOV', 'DEC': 'DEC', 'Shape_Leng': 'Shape_Leng', 'Shape_Area': 'Shape_Area', });
lyr_MactreAtlantique_AireConcentration_3.set('fieldAliases', {'NAME_EN': 'NAME_EN', 'NAME_FR': 'NAME_FR', 'NAME_SCI': 'NAME_SCI', 'NAME_OTHER': 'NAME_OTHER', 'LABEL_EN': 'LABEL_EN', 'LABEL_FR': 'LABEL_FR', 'URL': 'URL', 'URL_OTHER': 'URL_OTHER', 'LEGISLATIO': 'LEGISLATIO', 'LEGISLAT_1': 'LEGISLAT_1', 'JURISDICTI': 'JURISDICTI', 'JURISDIC_1': 'JURISDIC_1', 'GROUP_EN': 'GROUP_EN', 'GROUP_FR': 'GROUP_FR', 'SUBGROUP_E': 'SUBGROUP_E', 'SUBGROUP_F': 'SUBGROUP_F', 'STATUS_EN': 'STATUS_EN', 'STATUS_FR': 'STATUS_FR', 'DESCRIPTIO': 'DESCRIPTIO', 'DESCRIPT_1': 'DESCRIPT_1', 'VALIDATION': 'VALIDATION', 'PROVINCEEX': 'PROVINCEEX', 'ABUNDANCE': 'ABUNDANCE', 'DATASOURCE': 'DATASOURCE', 'STATUS_COD': 'STATUS_COD', 'SARA_EN': 'SARA_EN', 'SARA_FR': 'SARA_FR', 'SRANK_EN': 'SRANK_EN', 'SRANK_FR': 'SRANK_FR', 'COSEWIC_EN': 'COSEWIC_EN', 'COSEWIC_FR': 'COSEWIC_FR', 'LEMV_EN': 'LEMV_EN', 'LEMV_FR': 'LEMV_FR', 'GRANK_EN': 'GRANK_EN', 'GRANK_FR': 'GRANK_FR', 'ACTIVITY_E': 'ACTIVITY_E', 'ACTIVITY_F': 'ACTIVITY_F', 'LIFESTAGE_': 'LIFESTAGE_', 'LIFESTAGE1': 'LIFESTAGE1', 'IUCN_EN': 'IUCN_EN', 'IUCN_FR': 'IUCN_FR', 'SEASONALIT': 'SEASONALIT', 'SEASONAL_1': 'SEASONAL_1', 'JAN': 'JAN', 'FEB': 'FEB', 'MAR': 'MAR', 'APR': 'APR', 'MAY': 'MAY', 'JUN': 'JUN', 'JUL': 'JUL', 'AUG': 'AUG', 'SEP': 'SEP', 'OCT': 'OCT', 'NOV': 'NOV', 'DEC': 'DEC', 'Shape_Leng': 'Shape_Leng', 'Shape_Area': 'Shape_Area', });
lyr_MactreStimpson_AireConcentration_4.set('fieldAliases', {'NAME_EN': 'NAME_EN', 'NAME_FR': 'NAME_FR', 'NAME_SCI': 'NAME_SCI', 'NAME_OTHER': 'NAME_OTHER', 'LABEL_EN': 'LABEL_EN', 'LABEL_FR': 'LABEL_FR', 'URL': 'URL', 'URL_OTHER': 'URL_OTHER', 'LEGISLATIO': 'LEGISLATIO', 'LEGISLAT_1': 'LEGISLAT_1', 'JURISDICTI': 'JURISDICTI', 'JURISDIC_1': 'JURISDIC_1', 'GROUP_EN': 'GROUP_EN', 'GROUP_FR': 'GROUP_FR', 'SUBGROUP_E': 'SUBGROUP_E', 'SUBGROUP_F': 'SUBGROUP_F', 'STATUS_EN': 'STATUS_EN', 'STATUS_FR': 'STATUS_FR', 'DESCRIPTIO': 'DESCRIPTIO', 'DESCRIPT_1': 'DESCRIPT_1', 'VALIDATION': 'VALIDATION', 'PROVINCEEX': 'PROVINCEEX', 'REGION_EN': 'REGION_EN', 'REGION_FR': 'REGION_FR', 'ABUNDANCE': 'ABUNDANCE', 'DATASOURCE': 'DATASOURCE', 'STATUS_COD': 'STATUS_COD', 'SARA_EN': 'SARA_EN', 'SARA_FR': 'SARA_FR', 'SRANK_EN': 'SRANK_EN', 'SRANK_FR': 'SRANK_FR', 'COSEWIC_EN': 'COSEWIC_EN', 'COSEWIC_FR': 'COSEWIC_FR', 'LEMV_EN': 'LEMV_EN', 'LEMV_FR': 'LEMV_FR', 'GRANK_EN': 'GRANK_EN', 'GRANK_FR': 'GRANK_FR', 'ACTIVITY_E': 'ACTIVITY_E', 'ACTIVITY_F': 'ACTIVITY_F', 'LIFESTAGE_': 'LIFESTAGE_', 'LIFESTAGE1': 'LIFESTAGE1', 'IUCN_EN': 'IUCN_EN', 'IUCN_FR': 'IUCN_FR', 'SEASONALIT': 'SEASONALIT', 'SEASONAL_1': 'SEASONAL_1', 'JAN': 'JAN', 'FEB': 'FEB', 'MAR': 'MAR', 'APR': 'APR', 'MAY': 'MAY', 'JUN': 'JUN', 'JUL': 'JUL', 'AUG': 'AUG', 'SEP': 'SEP', 'OCT': 'OCT', 'NOV': 'NOV', 'DEC': 'DEC', 'Shape_Leng': 'Shape_Leng', 'Shape_Area': 'Shape_Area', });
lyr_MyeCommune_AireConcentration_5.set('fieldAliases', {'NAME_EN': 'NAME_EN', 'NAME_FR': 'NAME_FR', 'NAME_SCI': 'NAME_SCI', 'NAME_OTHER': 'NAME_OTHER', 'LABEL_EN': 'LABEL_EN', 'LABEL_FR': 'LABEL_FR', 'URL': 'URL', 'URL_OTHER': 'URL_OTHER', 'LEGISLATIO': 'LEGISLATIO', 'LEGISLAT_1': 'LEGISLAT_1', 'JURISDICTI': 'JURISDICTI', 'JURISDIC_1': 'JURISDIC_1', 'GROUP_EN': 'GROUP_EN', 'GROUP_FR': 'GROUP_FR', 'SUBGROUP_E': 'SUBGROUP_E', 'SUBGROUP_F': 'SUBGROUP_F', 'STATUS_EN': 'STATUS_EN', 'STATUS_FR': 'STATUS_FR', 'DESCRIPTIO': 'DESCRIPTIO', 'DESCRIPT_1': 'DESCRIPT_1', 'VALIDATION': 'VALIDATION', 'PROVINCEEX': 'PROVINCEEX', 'REGION_EN': 'REGION_EN', 'REGION_FR': 'REGION_FR', 'ABUNDANCE': 'ABUNDANCE', 'DATASOURCE': 'DATASOURCE', 'STATUS_COD': 'STATUS_COD', 'SARA_EN': 'SARA_EN', 'SARA_FR': 'SARA_FR', 'SRANK_EN': 'SRANK_EN', 'SRANK_FR': 'SRANK_FR', 'COSEWIC_EN': 'COSEWIC_EN', 'COSEWIC_FR': 'COSEWIC_FR', 'LEMV_EN': 'LEMV_EN', 'LEMV_FR': 'LEMV_FR', 'GRANK_EN': 'GRANK_EN', 'GRANK_FR': 'GRANK_FR', 'ACTIVITY_E': 'ACTIVITY_E', 'ACTIVITY_F': 'ACTIVITY_F', 'LIFESTAGE_': 'LIFESTAGE_', 'LIFESTAGE1': 'LIFESTAGE1', 'IUCN_EN': 'IUCN_EN', 'IUCN_FR': 'IUCN_FR', 'SEASONALIT': 'SEASONALIT', 'SEASONAL_1': 'SEASONAL_1', 'JAN': 'JAN', 'FEB': 'FEB', 'MAR': 'MAR', 'APR': 'APR', 'MAY': 'MAY', 'JUN': 'JUN', 'JUL': 'JUL', 'AUG': 'AUG', 'SEP': 'SEP', 'OCT': 'OCT', 'NOV': 'NOV', 'DEC': 'DEC', 'Shape_Leng': 'Shape_Leng', 'Shape_Area': 'Shape_Area', });
lyr_Petoncles_AireConcentration_6.set('fieldAliases', {'NAME_EN': 'NAME_EN', 'NAME_FR': 'NAME_FR', 'NAME_SCI': 'NAME_SCI', 'NAME_OTHER': 'NAME_OTHER', 'LABEL_EN': 'LABEL_EN', 'LABEL_FR': 'LABEL_FR', 'URL': 'URL', 'URL_OTHER': 'URL_OTHER', 'LEGISLATIO': 'LEGISLATIO', 'LEGISLAT_1': 'LEGISLAT_1', 'JURISDICTI': 'JURISDICTI', 'JURISDIC_1': 'JURISDIC_1', 'GROUP_EN': 'GROUP_EN', 'GROUP_FR': 'GROUP_FR', 'SUBGROUP_E': 'SUBGROUP_E', 'SUBGROUP_F': 'SUBGROUP_F', 'STATUS_EN': 'STATUS_EN', 'STATUS_FR': 'STATUS_FR', 'DESCRIPTIO': 'DESCRIPTIO', 'DESCRIPT_1': 'DESCRIPT_1', 'VALIDATION': 'VALIDATION', 'PROVINCEEX': 'PROVINCEEX', 'REGION_EN': 'REGION_EN', 'REGION_FR': 'REGION_FR', 'ABUNDANCE': 'ABUNDANCE', 'DATASOURCE': 'DATASOURCE', 'STATUS_COD': 'STATUS_COD', 'SARA_EN': 'SARA_EN', 'SARA_FR': 'SARA_FR', 'SRANK_EN': 'SRANK_EN', 'SRANK_FR': 'SRANK_FR', 'COSEWIC_EN': 'COSEWIC_EN', 'COSEWIC_FR': 'COSEWIC_FR', 'LEMV_EN': 'LEMV_EN', 'LEMV_FR': 'LEMV_FR', 'GRANK_EN': 'GRANK_EN', 'GRANK_FR': 'GRANK_FR', 'ACTIVITY_E': 'ACTIVITY_E', 'ACTIVITY_F': 'ACTIVITY_F', 'LIFESTAGE_': 'LIFESTAGE_', 'LIFESTAGE1': 'LIFESTAGE1', 'IUCN_EN': 'IUCN_EN', 'IUCN_FR': 'IUCN_FR', 'SEASONALIT': 'SEASONALIT', 'SEASONAL_1': 'SEASONAL_1', 'JAN': 'JAN', 'FEB': 'FEB', 'MAR': 'MAR', 'APR': 'APR', 'MAY': 'MAY', 'JUN': 'JUN', 'JUL': 'JUL', 'AUG': 'AUG', 'SEP': 'SEP', 'OCT': 'OCT', 'NOV': 'NOV', 'DEC': 'DEC', 'Shape_Leng': 'Shape_Leng', 'Shape_Area': 'Shape_Area', });
lyr_ClovisseArctique_AireConcentration_1.set('fieldImages', {'NAME_EN': '', 'NAME_FR': '', 'NAME_SCI': '', 'NAME_OTHER': '', 'LABEL_EN': '', 'LABEL_FR': '', 'URL': '', 'URL_OTHER': '', 'LEGISLATIO': '', 'LEGISLAT_1': '', 'JURISDICTI': '', 'JURISDIC_1': '', 'GROUP_EN': '', 'GROUP_FR': '', 'SUBGROUP_E': '', 'SUBGROUP_F': '', 'STATUS_EN': '', 'STATUS_FR': '', 'DESCRIPTIO': '', 'DESCRIPT_1': '', 'VALIDATION': '', 'PROVINCEEX': '', 'REGION_EN': '', 'REGION_FR': '', 'ABUNDANCE': '', 'DATASOURCE': '', 'STATUS_COD': '', 'SARA_EN': '', 'SARA_FR': '', 'SRANK_EN': '', 'SRANK_FR': '', 'COSEWIC_EN': '', 'COSEWIC_FR': '', 'LEMV_EN': '', 'LEMV_FR': '', 'GRANK_EN': '', 'GRANK_FR': '', 'ACTIVITY_E': '', 'ACTIVITY_F': '', 'LIFESTAGE_': '', 'LIFESTAGE1': '', 'IUCN_EN': '', 'IUCN_FR': '', 'SEASONALIT': '', 'SEASONAL_1': '', 'JAN': '', 'FEB': '', 'MAR': '', 'APR': '', 'MAY': '', 'JUN': '', 'JUL': '', 'AUG': '', 'SEP': '', 'OCT': '', 'NOV': '', 'DEC': '', 'Shape_Leng': '', 'Shape_Area': '', });
lyr_CouteauAtlantique_AireConcentration_2.set('fieldImages', {'NAME_EN': '', 'NAME_FR': '', 'NAME_SCI': '', 'NAME_OTHER': '', 'LABEL_EN': '', 'LABEL_FR': '', 'URL': '', 'URL_OTHER': '', 'LEGISLATIO': '', 'LEGISLAT_1': '', 'JURISDICTI': '', 'JURISDIC_1': '', 'GROUP_EN': '', 'GROUP_FR': '', 'SUBGROUP_E': '', 'SUBGROUP_F': '', 'STATUS_EN': '', 'STATUS_FR': '', 'DESCRIPTIO': '', 'DESCRIPT_1': '', 'VALIDATION': '', 'PROVINCEEX': '', 'REGION_EN': '', 'REGION_FR': '', 'ABUNDANCE': '', 'DATASOURCE': '', 'STATUS_COD': '', 'SARA_EN': '', 'SARA_FR': '', 'SRANK_EN': '', 'SRANK_FR': '', 'COSEWIC_EN': '', 'COSEWIC_FR': '', 'LEMV_EN': '', 'LEMV_FR': '', 'GRANK_EN': '', 'GRANK_FR': '', 'ACTIVITY_E': '', 'ACTIVITY_F': '', 'LIFESTAGE_': '', 'LIFESTAGE1': '', 'IUCN_EN': '', 'IUCN_FR': '', 'SEASONALIT': '', 'SEASONAL_1': '', 'JAN': '', 'FEB': '', 'MAR': '', 'APR': '', 'MAY': '', 'JUN': '', 'JUL': '', 'AUG': '', 'SEP': '', 'OCT': '', 'NOV': '', 'DEC': '', 'Shape_Leng': '', 'Shape_Area': '', });
lyr_MactreAtlantique_AireConcentration_3.set('fieldImages', {'NAME_EN': '', 'NAME_FR': '', 'NAME_SCI': '', 'NAME_OTHER': '', 'LABEL_EN': '', 'LABEL_FR': '', 'URL': '', 'URL_OTHER': '', 'LEGISLATIO': '', 'LEGISLAT_1': '', 'JURISDICTI': '', 'JURISDIC_1': '', 'GROUP_EN': '', 'GROUP_FR': '', 'SUBGROUP_E': '', 'SUBGROUP_F': '', 'STATUS_EN': '', 'STATUS_FR': '', 'DESCRIPTIO': '', 'DESCRIPT_1': '', 'VALIDATION': '', 'PROVINCEEX': '', 'ABUNDANCE': '', 'DATASOURCE': '', 'STATUS_COD': '', 'SARA_EN': '', 'SARA_FR': '', 'SRANK_EN': '', 'SRANK_FR': '', 'COSEWIC_EN': '', 'COSEWIC_FR': '', 'LEMV_EN': '', 'LEMV_FR': '', 'GRANK_EN': '', 'GRANK_FR': '', 'ACTIVITY_E': '', 'ACTIVITY_F': '', 'LIFESTAGE_': '', 'LIFESTAGE1': '', 'IUCN_EN': '', 'IUCN_FR': '', 'SEASONALIT': '', 'SEASONAL_1': '', 'JAN': '', 'FEB': '', 'MAR': '', 'APR': '', 'MAY': '', 'JUN': '', 'JUL': '', 'AUG': '', 'SEP': '', 'OCT': '', 'NOV': '', 'DEC': '', 'Shape_Leng': '', 'Shape_Area': '', });
lyr_MactreStimpson_AireConcentration_4.set('fieldImages', {'NAME_EN': '', 'NAME_FR': '', 'NAME_SCI': '', 'NAME_OTHER': '', 'LABEL_EN': '', 'LABEL_FR': '', 'URL': '', 'URL_OTHER': '', 'LEGISLATIO': '', 'LEGISLAT_1': '', 'JURISDICTI': '', 'JURISDIC_1': '', 'GROUP_EN': '', 'GROUP_FR': '', 'SUBGROUP_E': '', 'SUBGROUP_F': '', 'STATUS_EN': '', 'STATUS_FR': '', 'DESCRIPTIO': '', 'DESCRIPT_1': '', 'VALIDATION': '', 'PROVINCEEX': '', 'REGION_EN': '', 'REGION_FR': '', 'ABUNDANCE': '', 'DATASOURCE': '', 'STATUS_COD': '', 'SARA_EN': '', 'SARA_FR': '', 'SRANK_EN': '', 'SRANK_FR': '', 'COSEWIC_EN': '', 'COSEWIC_FR': '', 'LEMV_EN': '', 'LEMV_FR': '', 'GRANK_EN': '', 'GRANK_FR': '', 'ACTIVITY_E': '', 'ACTIVITY_F': '', 'LIFESTAGE_': '', 'LIFESTAGE1': '', 'IUCN_EN': '', 'IUCN_FR': '', 'SEASONALIT': '', 'SEASONAL_1': '', 'JAN': '', 'FEB': '', 'MAR': '', 'APR': '', 'MAY': '', 'JUN': '', 'JUL': '', 'AUG': '', 'SEP': '', 'OCT': '', 'NOV': '', 'DEC': '', 'Shape_Leng': '', 'Shape_Area': '', });
lyr_MyeCommune_AireConcentration_5.set('fieldImages', {'NAME_EN': '', 'NAME_FR': '', 'NAME_SCI': '', 'NAME_OTHER': '', 'LABEL_EN': '', 'LABEL_FR': '', 'URL': '', 'URL_OTHER': '', 'LEGISLATIO': '', 'LEGISLAT_1': '', 'JURISDICTI': '', 'JURISDIC_1': '', 'GROUP_EN': '', 'GROUP_FR': '', 'SUBGROUP_E': '', 'SUBGROUP_F': '', 'STATUS_EN': '', 'STATUS_FR': '', 'DESCRIPTIO': '', 'DESCRIPT_1': '', 'VALIDATION': '', 'PROVINCEEX': '', 'REGION_EN': '', 'REGION_FR': '', 'ABUNDANCE': '', 'DATASOURCE': '', 'STATUS_COD': '', 'SARA_EN': '', 'SARA_FR': '', 'SRANK_EN': '', 'SRANK_FR': '', 'COSEWIC_EN': '', 'COSEWIC_FR': '', 'LEMV_EN': '', 'LEMV_FR': '', 'GRANK_EN': '', 'GRANK_FR': '', 'ACTIVITY_E': '', 'ACTIVITY_F': '', 'LIFESTAGE_': '', 'LIFESTAGE1': '', 'IUCN_EN': '', 'IUCN_FR': '', 'SEASONALIT': '', 'SEASONAL_1': '', 'JAN': '', 'FEB': '', 'MAR': '', 'APR': '', 'MAY': '', 'JUN': '', 'JUL': '', 'AUG': '', 'SEP': '', 'OCT': '', 'NOV': '', 'DEC': '', 'Shape_Leng': '', 'Shape_Area': '', });
lyr_Petoncles_AireConcentration_6.set('fieldImages', {'NAME_EN': '', 'NAME_FR': '', 'NAME_SCI': '', 'NAME_OTHER': '', 'LABEL_EN': '', 'LABEL_FR': '', 'URL': '', 'URL_OTHER': '', 'LEGISLATIO': '', 'LEGISLAT_1': '', 'JURISDICTI': '', 'JURISDIC_1': '', 'GROUP_EN': '', 'GROUP_FR': '', 'SUBGROUP_E': '', 'SUBGROUP_F': '', 'STATUS_EN': '', 'STATUS_FR': '', 'DESCRIPTIO': '', 'DESCRIPT_1': '', 'VALIDATION': '', 'PROVINCEEX': '', 'REGION_EN': '', 'REGION_FR': '', 'ABUNDANCE': '', 'DATASOURCE': '', 'STATUS_COD': '', 'SARA_EN': '', 'SARA_FR': '', 'SRANK_EN': '', 'SRANK_FR': '', 'COSEWIC_EN': '', 'COSEWIC_FR': '', 'LEMV_EN': '', 'LEMV_FR': '', 'GRANK_EN': '', 'GRANK_FR': '', 'ACTIVITY_E': '', 'ACTIVITY_F': '', 'LIFESTAGE_': '', 'LIFESTAGE1': '', 'IUCN_EN': '', 'IUCN_FR': '', 'SEASONALIT': '', 'SEASONAL_1': '', 'JAN': '', 'FEB': '', 'MAR': '', 'APR': '', 'MAY': '', 'JUN': '', 'JUL': '', 'AUG': '', 'SEP': '', 'OCT': '', 'NOV': '', 'DEC': '', 'Shape_Leng': '', 'Shape_Area': '', });
lyr_ClovisseArctique_AireConcentration_1.set('fieldLabels', {'NAME_EN': 'no label', 'NAME_FR': 'no label', 'NAME_SCI': 'no label', 'NAME_OTHER': 'no label', 'LABEL_EN': 'no label', 'LABEL_FR': 'no label', 'URL': 'no label', 'URL_OTHER': 'no label', 'LEGISLATIO': 'no label', 'LEGISLAT_1': 'no label', 'JURISDICTI': 'no label', 'JURISDIC_1': 'no label', 'GROUP_EN': 'no label', 'GROUP_FR': 'no label', 'SUBGROUP_E': 'no label', 'SUBGROUP_F': 'no label', 'STATUS_EN': 'no label', 'STATUS_FR': 'no label', 'DESCRIPTIO': 'no label', 'DESCRIPT_1': 'no label', 'VALIDATION': 'no label', 'PROVINCEEX': 'no label', 'REGION_EN': 'no label', 'REGION_FR': 'no label', 'ABUNDANCE': 'no label', 'DATASOURCE': 'no label', 'STATUS_COD': 'no label', 'SARA_EN': 'no label', 'SARA_FR': 'no label', 'SRANK_EN': 'no label', 'SRANK_FR': 'no label', 'COSEWIC_EN': 'no label', 'COSEWIC_FR': 'no label', 'LEMV_EN': 'no label', 'LEMV_FR': 'no label', 'GRANK_EN': 'no label', 'GRANK_FR': 'no label', 'ACTIVITY_E': 'no label', 'ACTIVITY_F': 'no label', 'LIFESTAGE_': 'no label', 'LIFESTAGE1': 'no label', 'IUCN_EN': 'no label', 'IUCN_FR': 'no label', 'SEASONALIT': 'no label', 'SEASONAL_1': 'no label', 'JAN': 'no label', 'FEB': 'no label', 'MAR': 'no label', 'APR': 'no label', 'MAY': 'no label', 'JUN': 'no label', 'JUL': 'no label', 'AUG': 'no label', 'SEP': 'no label', 'OCT': 'no label', 'NOV': 'no label', 'DEC': 'no label', 'Shape_Leng': 'no label', 'Shape_Area': 'no label', });
lyr_CouteauAtlantique_AireConcentration_2.set('fieldLabels', {'NAME_EN': 'no label', 'NAME_FR': 'no label', 'NAME_SCI': 'no label', 'NAME_OTHER': 'no label', 'LABEL_EN': 'no label', 'LABEL_FR': 'no label', 'URL': 'no label', 'URL_OTHER': 'no label', 'LEGISLATIO': 'no label', 'LEGISLAT_1': 'no label', 'JURISDICTI': 'no label', 'JURISDIC_1': 'no label', 'GROUP_EN': 'no label', 'GROUP_FR': 'no label', 'SUBGROUP_E': 'no label', 'SUBGROUP_F': 'no label', 'STATUS_EN': 'no label', 'STATUS_FR': 'no label', 'DESCRIPTIO': 'no label', 'DESCRIPT_1': 'no label', 'VALIDATION': 'no label', 'PROVINCEEX': 'no label', 'REGION_EN': 'no label', 'REGION_FR': 'no label', 'ABUNDANCE': 'no label', 'DATASOURCE': 'no label', 'STATUS_COD': 'no label', 'SARA_EN': 'no label', 'SARA_FR': 'no label', 'SRANK_EN': 'no label', 'SRANK_FR': 'no label', 'COSEWIC_EN': 'no label', 'COSEWIC_FR': 'no label', 'LEMV_EN': 'no label', 'LEMV_FR': 'no label', 'GRANK_EN': 'no label', 'GRANK_FR': 'no label', 'ACTIVITY_E': 'no label', 'ACTIVITY_F': 'no label', 'LIFESTAGE_': 'no label', 'LIFESTAGE1': 'no label', 'IUCN_EN': 'no label', 'IUCN_FR': 'no label', 'SEASONALIT': 'no label', 'SEASONAL_1': 'no label', 'JAN': 'no label', 'FEB': 'no label', 'MAR': 'no label', 'APR': 'no label', 'MAY': 'no label', 'JUN': 'no label', 'JUL': 'no label', 'AUG': 'no label', 'SEP': 'no label', 'OCT': 'no label', 'NOV': 'no label', 'DEC': 'no label', 'Shape_Leng': 'no label', 'Shape_Area': 'no label', });
lyr_MactreAtlantique_AireConcentration_3.set('fieldLabels', {'NAME_EN': 'no label', 'NAME_FR': 'no label', 'NAME_SCI': 'no label', 'NAME_OTHER': 'no label', 'LABEL_EN': 'no label', 'LABEL_FR': 'no label', 'URL': 'no label', 'URL_OTHER': 'no label', 'LEGISLATIO': 'no label', 'LEGISLAT_1': 'no label', 'JURISDICTI': 'no label', 'JURISDIC_1': 'no label', 'GROUP_EN': 'no label', 'GROUP_FR': 'no label', 'SUBGROUP_E': 'no label', 'SUBGROUP_F': 'no label', 'STATUS_EN': 'no label', 'STATUS_FR': 'no label', 'DESCRIPTIO': 'no label', 'DESCRIPT_1': 'no label', 'VALIDATION': 'no label', 'PROVINCEEX': 'no label', 'ABUNDANCE': 'no label', 'DATASOURCE': 'no label', 'STATUS_COD': 'no label', 'SARA_EN': 'no label', 'SARA_FR': 'no label', 'SRANK_EN': 'no label', 'SRANK_FR': 'no label', 'COSEWIC_EN': 'no label', 'COSEWIC_FR': 'no label', 'LEMV_EN': 'no label', 'LEMV_FR': 'no label', 'GRANK_EN': 'no label', 'GRANK_FR': 'no label', 'ACTIVITY_E': 'no label', 'ACTIVITY_F': 'no label', 'LIFESTAGE_': 'no label', 'LIFESTAGE1': 'no label', 'IUCN_EN': 'no label', 'IUCN_FR': 'no label', 'SEASONALIT': 'no label', 'SEASONAL_1': 'no label', 'JAN': 'no label', 'FEB': 'no label', 'MAR': 'no label', 'APR': 'no label', 'MAY': 'no label', 'JUN': 'no label', 'JUL': 'no label', 'AUG': 'no label', 'SEP': 'no label', 'OCT': 'no label', 'NOV': 'no label', 'DEC': 'no label', 'Shape_Leng': 'no label', 'Shape_Area': 'no label', });
lyr_MactreStimpson_AireConcentration_4.set('fieldLabels', {'NAME_EN': 'no label', 'NAME_FR': 'no label', 'NAME_SCI': 'no label', 'NAME_OTHER': 'no label', 'LABEL_EN': 'no label', 'LABEL_FR': 'no label', 'URL': 'no label', 'URL_OTHER': 'no label', 'LEGISLATIO': 'no label', 'LEGISLAT_1': 'no label', 'JURISDICTI': 'no label', 'JURISDIC_1': 'no label', 'GROUP_EN': 'no label', 'GROUP_FR': 'no label', 'SUBGROUP_E': 'no label', 'SUBGROUP_F': 'no label', 'STATUS_EN': 'no label', 'STATUS_FR': 'no label', 'DESCRIPTIO': 'no label', 'DESCRIPT_1': 'no label', 'VALIDATION': 'no label', 'PROVINCEEX': 'no label', 'REGION_EN': 'no label', 'REGION_FR': 'no label', 'ABUNDANCE': 'no label', 'DATASOURCE': 'no label', 'STATUS_COD': 'no label', 'SARA_EN': 'no label', 'SARA_FR': 'no label', 'SRANK_EN': 'no label', 'SRANK_FR': 'no label', 'COSEWIC_EN': 'no label', 'COSEWIC_FR': 'no label', 'LEMV_EN': 'no label', 'LEMV_FR': 'no label', 'GRANK_EN': 'no label', 'GRANK_FR': 'no label', 'ACTIVITY_E': 'no label', 'ACTIVITY_F': 'no label', 'LIFESTAGE_': 'no label', 'LIFESTAGE1': 'no label', 'IUCN_EN': 'no label', 'IUCN_FR': 'no label', 'SEASONALIT': 'no label', 'SEASONAL_1': 'no label', 'JAN': 'no label', 'FEB': 'no label', 'MAR': 'no label', 'APR': 'no label', 'MAY': 'no label', 'JUN': 'no label', 'JUL': 'no label', 'AUG': 'no label', 'SEP': 'no label', 'OCT': 'no label', 'NOV': 'no label', 'DEC': 'no label', 'Shape_Leng': 'no label', 'Shape_Area': 'no label', });
lyr_MyeCommune_AireConcentration_5.set('fieldLabels', {'NAME_EN': 'no label', 'NAME_FR': 'no label', 'NAME_SCI': 'no label', 'NAME_OTHER': 'no label', 'LABEL_EN': 'no label', 'LABEL_FR': 'no label', 'URL': 'no label', 'URL_OTHER': 'no label', 'LEGISLATIO': 'no label', 'LEGISLAT_1': 'no label', 'JURISDICTI': 'no label', 'JURISDIC_1': 'no label', 'GROUP_EN': 'no label', 'GROUP_FR': 'no label', 'SUBGROUP_E': 'no label', 'SUBGROUP_F': 'no label', 'STATUS_EN': 'no label', 'STATUS_FR': 'no label', 'DESCRIPTIO': 'no label', 'DESCRIPT_1': 'no label', 'VALIDATION': 'no label', 'PROVINCEEX': 'no label', 'REGION_EN': 'no label', 'REGION_FR': 'no label', 'ABUNDANCE': 'no label', 'DATASOURCE': 'no label', 'STATUS_COD': 'no label', 'SARA_EN': 'no label', 'SARA_FR': 'no label', 'SRANK_EN': 'no label', 'SRANK_FR': 'no label', 'COSEWIC_EN': 'no label', 'COSEWIC_FR': 'no label', 'LEMV_EN': 'no label', 'LEMV_FR': 'no label', 'GRANK_EN': 'no label', 'GRANK_FR': 'no label', 'ACTIVITY_E': 'no label', 'ACTIVITY_F': 'no label', 'LIFESTAGE_': 'no label', 'LIFESTAGE1': 'no label', 'IUCN_EN': 'no label', 'IUCN_FR': 'no label', 'SEASONALIT': 'no label', 'SEASONAL_1': 'no label', 'JAN': 'no label', 'FEB': 'no label', 'MAR': 'no label', 'APR': 'no label', 'MAY': 'no label', 'JUN': 'no label', 'JUL': 'no label', 'AUG': 'no label', 'SEP': 'no label', 'OCT': 'no label', 'NOV': 'no label', 'DEC': 'no label', 'Shape_Leng': 'no label', 'Shape_Area': 'no label', });
lyr_Petoncles_AireConcentration_6.set('fieldLabels', {'NAME_EN': 'no label', 'NAME_FR': 'no label', 'NAME_SCI': 'no label', 'NAME_OTHER': 'no label', 'LABEL_EN': 'no label', 'LABEL_FR': 'no label', 'URL': 'no label', 'URL_OTHER': 'no label', 'LEGISLATIO': 'no label', 'LEGISLAT_1': 'no label', 'JURISDICTI': 'no label', 'JURISDIC_1': 'no label', 'GROUP_EN': 'no label', 'GROUP_FR': 'no label', 'SUBGROUP_E': 'no label', 'SUBGROUP_F': 'no label', 'STATUS_EN': 'no label', 'STATUS_FR': 'no label', 'DESCRIPTIO': 'no label', 'DESCRIPT_1': 'no label', 'VALIDATION': 'no label', 'PROVINCEEX': 'no label', 'REGION_EN': 'no label', 'REGION_FR': 'no label', 'ABUNDANCE': 'no label', 'DATASOURCE': 'no label', 'STATUS_COD': 'no label', 'SARA_EN': 'no label', 'SARA_FR': 'no label', 'SRANK_EN': 'no label', 'SRANK_FR': 'no label', 'COSEWIC_EN': 'no label', 'COSEWIC_FR': 'no label', 'LEMV_EN': 'no label', 'LEMV_FR': 'no label', 'GRANK_EN': 'no label', 'GRANK_FR': 'no label', 'ACTIVITY_E': 'no label', 'ACTIVITY_F': 'no label', 'LIFESTAGE_': 'no label', 'LIFESTAGE1': 'no label', 'IUCN_EN': 'no label', 'IUCN_FR': 'no label', 'SEASONALIT': 'no label', 'SEASONAL_1': 'no label', 'JAN': 'no label', 'FEB': 'no label', 'MAR': 'no label', 'APR': 'no label', 'MAY': 'no label', 'JUN': 'no label', 'JUL': 'no label', 'AUG': 'no label', 'SEP': 'no label', 'OCT': 'no label', 'NOV': 'no label', 'DEC': 'no label', 'Shape_Leng': 'no label', 'Shape_Area': 'no label', });
lyr_Petoncles_AireConcentration_6.on('precompose', function(evt) {
    evt.context.globalCompositeOperation = 'normal';
});